export const REPORT_MARKER = "<!-- Generated by Modular. Changes to this file may be replaced by the next scan. -->";
export const REPORT_LOCK_FILE = ".modular-report.lock";
export const REPORT_LOCK_MARKER = "modular-report-lock-v1";
export const DEFAULT_REPORT_LOCK_TIMEOUT_MS = 15_000;
export const DEFAULT_REPORT_LOCK_STALE_MS = 30_000;
