export const CHECK_IDS = Object.freeze([
  "website-project-detection",
  "robots-directives",
  "xml-sitemap",
  "page-indexability",
  "document-title",
  "meta-description",
  "canonical-url",
  "social-sharing-metadata",
  "structured-data",
  "geo-aeo-aio-readiness",
  "document-language",
  "character-encoding",
  "viewport-configuration",
  "heading-hierarchy",
  "heading-content-and-uniqueness",
  "markdown-content-and-frontmatter",
  "semantic-landmarks",
  "accessible-images",
  "accessible-controls",
  "descriptive-links",
  "keyboard-navigation",
  "focus-visibility",
  "screen-reader-support",
  "media-alternatives",
  "autoplay-media",
  "aria-hidden-focus-safety",
  "form-labels",
  "form-validation",
  "form-error-feedback",
  "form-purpose-and-submit-behavior",
  "responsive-layout",
  "responsive-breakpoints",
  "mobile-first-readiness",
  "touch-targets",
  "typography-readability",
  "color-contrast",
  "reduced-motion",
  "layout-stability",
  "image-delivery",
  "priority-image-loading",
  "render-blocking-resources",
  "source-payload-size",
  "core-web-vitals-readiness",
  "loading-states",
  "error-states",
  "empty-states",
  "not-found-experience",
  "navigation-information-architecture",
  "search-filtering-sorting",
  "onboarding-personalization",
  "interaction-feedback",
  "design-system-consistency",
  "component-reusability",
  "cross-browser-compatibility",
  "cross-platform-compatibility",
  "transport-and-link-security",
  "privacy-consent",
  "trust-credibility",
  "analytics-measurement",
  "conversion-cta",
  "experimentation-ab-testing",
]);

// These families cannot be completed from repository text alone. They remain
// configured so the report can queue the relevant review, but must not be
// presented as automated checks merely because their names are in CHECK_IDS.
const MANUAL_CHECK_IDS = new Set([
  "geo-aeo-aio-readiness",
  "touch-targets",
  "color-contrast",
  "core-web-vitals-readiness",
  "search-filtering-sorting",
  "onboarding-personalization",
  "trust-credibility",
  "analytics-measurement",
  "conversion-cta",
  "experimentation-ab-testing",
]);

// Finding ids are deliberately more specific than the public rule-family
// catalog. Keep this mapping exhaustive so related locations and static/runtime
// confirmations contribute once to the risk model instead of stacking.
export const RULE_FAMILY_BY_FINDING = Object.freeze({
  "a11y-audible-autoplay": "autoplay-media",
  "a11y-clickable-noncontrol": "accessible-controls",
  "a11y-control-name": "accessible-controls",
  "a11y-dialog-name": "screen-reader-support",
  "a11y-document-language": "document-language",
  "a11y-duplicate-id": "screen-reader-support",
  "a11y-fieldset-legend": "form-labels",
  "a11y-focus-indicator-removed": "focus-visibility",
  "a11y-focusable-aria-hidden": "aria-hidden-focus-safety",
  "a11y-form-label": "form-labels",
  "a11y-iframe-title": "screen-reader-support",
  "a11y-image-alt": "accessible-images",
  "a11y-image-input-alt": "accessible-controls",
  "a11y-interactive-nesting": "accessible-controls",
  "a11y-link-name": "descriptive-links",
  "a11y-markdown-image-alt-review": "accessible-images",
  "a11y-meta-refresh": "screen-reader-support",
  "a11y-missing-main-landmark": "semantic-landmarks",
  "a11y-motion-no-reduction": "reduced-motion",
  "a11y-positive-tabindex": "keyboard-navigation",
  "a11y-svg-image-name": "accessible-images",
  "a11y-table-name": "semantic-landmarks",
  "a11y-video-captions": "media-alternatives",
  "a11y-viewport-zoom": "viewport-configuration",
  "compat-browser-global-on-server": "cross-platform-compatibility",
  "compat-no-browser-policy": "cross-browser-compatibility",
  "compat-no-browser-tests": "cross-browser-compatibility",
  "content-empty-heading": "heading-content-and-uniqueness",
  "content-heading-jump": "heading-hierarchy",
  "content-missing-h1": "heading-content-and-uniqueness",
  "content-multiple-h1": "heading-content-and-uniqueness",
  "crawl-invalid-robots": "robots-directives",
  "crawl-invalid-sitemap-directive": "robots-directives",
  "crawl-invalid-sitemap": "xml-sitemap",
  "crawl-invalid-sitemap-location": "xml-sitemap",
  "crawl-insecure-sitemap-location": "xml-sitemap",
  "crawl-duplicate-sitemap-location": "xml-sitemap",
  "crawl-empty-sitemap": "xml-sitemap",
  "crawl-sitemap-namespace": "xml-sitemap",
  "crawl-missing-robots": "robots-directives",
  "crawl-missing-sitemap": "xml-sitemap",
  "crawl-robots-missing-sitemap": "robots-directives",
  "crawl-unsupported-noindex": "robots-directives",
  "crawl-robots-unvalidated": "robots-directives",
  "crawl-sitemap-unvalidated": "xml-sitemap",
  "crawl-sitewide-disallow": "page-indexability",
  "design-large-component": "component-reusability",
  "design-no-color-tokens": "design-system-consistency",
  "discoverability-no-structured-data": "structured-data",
  "forms-implicit-button-type": "form-purpose-and-submit-behavior",
  "forms-missing-autocomplete": "form-purpose-and-submit-behavior",
  "forms-no-error-feedback-signal": "form-error-feedback",
  "forms-no-validation-signal": "form-validation",
  "html-missing-charset": "character-encoding",
  "manual-conversion-measurement-review": "conversion-cta",
  "manual-cwv-browser-review": "core-web-vitals-readiness",
  "manual-discoverability-review": "geo-aeo-aio-readiness",
  "manual-responsive-a11y-review": "touch-targets",
  "manual-user-flow-review": "onboarding-personalization",
  "manual-visual-ux-review": "color-contrast",
  "performance-font-display": "render-blocking-resources",
  "performance-css-import": "render-blocking-resources",
  "performance-large-font-asset": "source-payload-size",
  "performance-large-gif-asset": "image-delivery",
  "performance-large-image-asset": "image-delivery",
  "performance-large-media-asset": "source-payload-size",
  "performance-large-wasm-asset": "source-payload-size",
  "performance-legacy-image-format": "image-delivery",
  "performance-image-dimensions": "layout-stability",
  "performance-large-source-file": "source-payload-size",
  "performance-priority-image-lazy": "priority-image-loading",
  "performance-render-blocking-script": "render-blocking-resources",
  "performance-transition-all": "reduced-motion",
  "privacy-analytics-without-consent-signal": "privacy-consent",
  "privacy-password-get-form": "form-purpose-and-submit-behavior",
  "privacy-sensitive-browser-storage": "privacy-consent",
  "project-invalid-package-json": "website-project-detection",
  "responsive-missing-viewport": "viewport-configuration",
  "responsive-no-breakpoint-strategy": "responsive-breakpoints",
  "responsive-rigid-width": "responsive-layout",
  "security-external-link-opener": "transport-and-link-security",
  "security-insecure-resource": "transport-and-link-security",
  "seo-duplicate-static-title": "document-title",
  "seo-duplicate-static-description": "meta-description",
  "seo-insecure-canonical": "canonical-url",
  "seo-invalid-canonical": "canonical-url",
  "seo-invalid-structured-data": "structured-data",
  "seo-markdown-empty-canonical": "canonical-url",
  "seo-markdown-empty-description": "meta-description",
  "seo-markdown-empty-title": "document-title",
  "seo-markdown-missing-description": "meta-description",
  "seo-missing-canonical": "canonical-url",
  "seo-missing-description": "meta-description",
  "seo-missing-social-metadata": "social-sharing-metadata",
  "seo-incomplete-social-metadata": "social-sharing-metadata",
  "seo-invalid-social-url": "social-sharing-metadata",
  "seo-missing-title": "document-title",
  "seo-multiple-canonicals": "canonical-url",
  "seo-multiple-titles": "document-title",
  "seo-page-noindex": "page-indexability",
  "ux-ambiguous-link-text": "descriptive-links",
  "ux-document-scroll-disabled": "responsive-layout",
  "ux-missing-navigation-landmark": "navigation-information-architecture",
  "ux-no-empty-state": "empty-states",
  "ux-no-error-state": "error-states",
  "ux-no-loading-state": "loading-states",
  "ux-no-not-found-page": "not-found-experience",
  "ux-small-text": "typography-readability",
});

export function checkDescriptors(applicabilityById = {}) {
  return CHECK_IDS.map((id) => {
    const manual = MANUAL_CHECK_IDS.has(id);
    const applicable = applicabilityById[id];
    const applicability = applicable === true
      ? "applicable"
      : (applicable === false ? "not-applicable" : "unknown");
    const status = applicable === true
      ? (manual ? "applicable" : "completed")
      : (applicable === false ? "not-applicable" : "unknown");
    const executionStatus = applicable === true
      ? (manual ? "queued-for-human-review" : "completed")
      : (applicable === false ? "not-applicable" : "not-evaluated");
    return { id, kind: manual ? "manual" : "automated", executionStatus, applicability, status };
  });
}
